config/routes.rb
CampagneBed::Application.routes.draw do
  get "logs", to: 'logs#index'
  devise_for :admins
  resources :items

  resources :chat, only: [:index, :create, :destroy]

  get 'home', to: 'home#index'
  get 'challenges', to: 'home#challenges'
  get 'wall', to: 'home#wall'

  root 'home#index'

  

end

app/models/admin.rb
class Admin < ActiveRecord::Base

  devise :invitable, :database_authenticatable, :timeoutable,
         :trackable, :validatable


  def name
    email.split('@').first
  end

end

app/models/chat.rb
class Chat < ActiveRecord::Base

  validates :message, presence: true, length: {in: 1..140}
  validates :pseudo, presence: true, length: {in: 2..20}

end

app/models/item.rb
class Item < ActiveRecord::Base

  default_scope order('created_at DESC')

  LIST_NAMES = ["Liste 1", "Liste 2", "Liste 3"]

  validates :title, presence: true
  validates :list, presence: true, inclusion: {in: -1.upto(LIST_NAMES.length-1)}
  validates :points, presence: true, numericality: {only_integer: true}


  def list_name
    if challenge?
      "Challenge"
    else
      LIST_NAMES[list]
    end
  end

  def challenge?
    list == -1
  end

  def self.total_points list
    Item.where('list = ?', list).sum(:points)
  end

  def self.best_list
    0.upto(LIST_NAMES.length-1).map { |l| total_points l }.each_with_index.max[1]
  end

end

app/models/log.rb
class Log < ActiveRecord::Base

  belongs_to :admin
  belongs_to :item

  default_scope order('created_at DESC')

  validates :content, presence: true
  validates :admin, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_filter :authenticate_admin!

end

app/controllers/chat_controller.rb
class ChatController < ApplicationController

  skip_filter :authenticate_admin!, only: [:create]

  def index
    @chats = Chat.all.order('created_at desc')
  end

  def create
    @chat = Chat.new(chat_params)
    @chat.ip = request.remote_ip
    if @chat.save
      redirect_to wall_url
    else
      redirect_to wall_url, notice: 'chat was successfully created.'
    end
  end

  def destroy
    @chat = Chat.find(params[:id])
    if @chat.destroy
      Log.create admin: current_admin, content: "Chat destroyed. Old params were: pseudo=#{@chat.pseudo} ; message=#{@chat.message}."
      redirect_to chat_index_url
    end
  end


  private

  def chat_params
    params.require(:chat).permit(:pseudo, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  skip_filter :authenticate_admin!

  def index
    @items = Item.where('list >= 0')
    @best_list = Item.best_list
  end

  def challenges
    @items = Item.where('list = -1')
  end

  def wall
    @chats = Chat.all.limit(50).order('created_at desc')
    @chat = Chat.new
  end

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
        Log.create admin: current_admin, item: @item, content: "Item created with params: list=#{@item.list_name} ; points=#{@item.points} ; title=#{@item.title}"
        format.html { redirect_to items_url, notice: 'Item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @item }
      else
        format.html { render action: 'new' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    old_item = OpenStruct.new list_name: @item.list_name, points: @item.points, title: @item.title
    if @item.challenge? && params[:list].to_i > -1
      @item.created_at = DateTime.now
    end
    respond_to do |format|
      if @item.update(item_params)
        Log.create admin: current_admin, item: @item, content: "Item updated with params: list=#{@item.list_name} ; points=#{@item.points} ; title=#{@item.title}. Old params were: list=#{old_item.list_name} ; points=#{old_item.points} ; title=#{old_item.title}"
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      Log.create admin: current_admin, item: @item, content: "Item destroyed. Old params were: list=#{@item.list_name} ; points=#{@item.points} ; title=#{@item.title}."
      format.html { redirect_to items_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:title, :list, :points)
    end
end

app/controllers/logs_controller.rb
class LogsController < ApplicationController

  def index
    @logs = Log.limit(100)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chat_helper.rb
module ChatHelper
end

app/helpers/home_helper.rb
module HomeHelper

  def auto_link s
    s.gsub! /((http:\/\/|https:\/\/)?(www.)?(([a-zA-Z0-9-]){2,}\.){1,4}([a-zA-Z]){2,6}(\/([a-zA-Z-_\/\.0-9#:?=&;,]*)?)?)/ do |url| 
      "<a href='#{url}'>#{url}</a>"
    end
    sanitize s, tags: %w{a}
  end

end

app/helpers/items_helper.rb
module ItemsHelper

  def list_select_options
    [["Challenge",-1]].concat Item::LIST_NAMES.map.with_index { |l,i| [l,i] }
  end

end

app/helpers/logs_helper.rb
module LogsHelper
end

app/views/chat/index.html.erb
<h1>Chat</h1>

<table class="table items-table">
  <thead>
    <tr>
      <th>Pseudo</th>
      <th>Message</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @chats.each do |chat| %>
      <tr>
        <td><%= chat.pseudo %> [<%= chat.ip %>]</td>
        <td><%= chat.message %></td>
        <td><%= chat.created_at.to_s %></td>
        <td>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      chat_path(chat),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/_scores.html.erb
<ul class="scores">
  <li>
    <%= link_to image_tag("list0.jpg", alt: "Liste 1"), "http://liste1.com" %>
    Baba Forum
    <strong><%= Item.total_points 0 %> <small>pts</small></strong>
  </li>
  <li>
    <%= link_to image_tag("list1.jpg", alt: "Liste 2"), "http://liste2.com" %>
    Forum Boyard
    <strong><%= Item.total_points 1 %> <small>pts</small></strong>
  </li>
  <li>
    <%= link_to image_tag("list2.jpg", alt: "Liste 3"), "http://liste3.com" %>
    Forum Boyard
    <strong><%= Item.total_points 2 %> <small>pts</small></strong>
  </li>
</ul>

app/views/home/challenges.html.erb
<header>
  <h1>Challenges</h1>

  <% if @items.empty? %>
    <p class="big-link">Aucun challenge pour le moment :(</p>
  <% else %>
  <ul class="items challenges">
    <% @items.each do |i| %>
      <li>
        <strong><%= i.points %> <small>pts</small></strong>
        <%=auto_link i.title %>
      </li>
    <% end %>
  </ul>
  <% end %>
</header>

<p class="big-link"><%= link_to "Retour à l'accueil", root_path %></p>

app/views/home/index.html.erb
<header>
  <h1>Pour qui faut-il voter ?</h1>

  <p class="best-list">
    <% if (Item.total_points(0) == Item.total_points(1) and Item.total_points(2) == Item.total_points(0)) or
	      (Item.total_points(0) == Item.total_points(1) and Item.total_points(0) > Item.total_points(2)) or
		  (Item.total_points(0) == Item.total_points(2) and Item.total_points(0) > Item.total_points(1)) or
		  (Item.total_points(1) == Item.total_points(2) and Item.total_points(1) > Item.total_points(0)) %>
    <%= image_tag "bedzoum.png", alt: "BEDzoum" %>
    Il faut voter <strong>BEDzoum</strong>
    <small>Parce qu'en cas d'égalité, ce sont toujours eux qui gagnent.</small>
    <% else %>
    <%= image_tag "list#{@best_list}.jpg", alt: Item::LIST_NAMES[@best_list] %>
    Il faut voter <strong><%= Item::LIST_NAMES[@best_list] %></strong>
    <% end %>
  </p>

  <div class="boxes">
    <%= link_to challenges_path do %>
      <div class="box">
        <h2>Challenges</h2>
        <%= image_tag "cup.svg", alt: "Challenges" %>
      </div>
    <% end %>

    <%= link_to wall_path do %>
      <div class="box">
        <h2>The Wall</h2>
        <%= image_tag "chat.svg", alt: "The Wall" %>
      </div>
    <% end %>
  </div>
</header>




<h2>Détails</h2>

<%= render 'scores' %>

<ul class="items">
<% @items.each do |i| %>
  <li class="list<%= i.list %>">
    <strong class="<%= if i.points > 0 then 'pos' else 'neg' end %>">
      <%= image_tag "list#{i.list}.jpg", alt: Item::LIST_NAMES[@best_list] %>
      <%= i.points %> <small>pts</small>
    </strong>
    <%=auto_link i.title %>
  </li>
<% end %>
</ul>

app/views/home/wall.html.erb
<header>
  <h1>The Wall</h1>

  <%= form_for @chat, url: chat_index_path do |f| %>
    <%= f.text_field :pseudo, placeholder: "Pseudo" %>
    <%= f.text_field :message, placeholder: "Message", autofocus: true %>
    <%= f.submit value: "Go" %>
  <% end %>

  <% if @chats.empty? %>
    <p class="big-link">Aucun message pour le moment :(</p>
  <% else %>
    <dl class="chats">
      <% @chats.each do |chat| %>
        <dt>
          <time datetime="<%= chat.created_at %>"><%= time_ago_in_words chat.created_at %></time>
          <%= chat.pseudo %>
        </dt>
        <dd>
          <%= chat.message %>
        </dd>
      <% end %>
    </dl>
  <% end %>
</header>

<p class="big-link"><%= link_to "Retour à l'accueil", root_path %></p>

app/views/items/_form.html.erb
<% if @item.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@item.errors.count, "error") %> prohibited this item from being saved:</h2>

    <ul>
    <% @item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_for @item, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :title, :class => 'control-label' %>
    <%= f.text_area :title, :class => 'text_field', required: true %>
  </div>
  <div class="control-group">
    <%= f.label :list, :class => 'control-label' %>
    <%= f.select :list, list_select_options, class: 'text_field' %>
  </div>
  <div class="control-group">
    <%= f.label :points, :class => 'control-label' %>
    <%= f.text_field :points, :class => 'text_field', required: true %>
  </div>

  <div class="form-actions">
    <%= f.submit "Go!", :class => 'btn btn-primary' %>
    <%= link_to "Annuler", items_path %>
  </div>
<% end %>

app/views/items/edit.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/index.html.erb
<%- model_class = Item -%>

<h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>

<p><%= link_to '+ New item +', new_item_path, :class => 'new-item' %></p>


<table class="table items-table">
  <thead>
    <tr>
      <th>Content</th>
      <th>List</th>
      <th>Pts</th>
      <th>Created at</th>
      <th>Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= item.title %></td>
        <td>
          <% if item.challenge? %>
            <span class="challenge-label">Challenge</span>
          <% else %>
            <%= item.list_name %>
          <% end %>
        </td>
        <td><%= item.points %></td>
        <td><%= item.created_at.to_s %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_item_path(item), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      item_path(item),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) } %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/items/new.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/items/show.html.erb
<%- model_class = Item -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= @item.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:list) %>:</strong></dt>
  <dd><%= @item.list %></dd>
  <dt><strong><%= model_class.human_attribute_name(:points) %>:</strong></dt>
  <dd><%= @item.points %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              items_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_item_path(@item), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              item_path(@item),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pour qui faut-il voter ?</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <link href='https://fonts.googleapis.com/css?family=Roboto:300,100' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>



    <div class="container-fluid">
      <nav>
        <ul>
          <li><%= link_to "Back to home page", home_path %></li>
          <% if current_admin %>
          <li><%= link_to "Item list", items_path %></li>
          <li><%= link_to "Chat", chat_index_path %></li>
          <li><%= link_to "Invitations", new_admin_invitation_path %></li>
          <li><%= link_to "Logs", logs_path %></li>
        </ul>
        <ul class="right">
          <li>Hello <%= current_admin.name %></li>
          <li><%= link_to "Logout", destroy_admin_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </nav>

      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>

      <%= yield %>


      <footer>
        <p>Made with love in A406 - <%= link_to "Fork me on GitHub", "https://github.com/allegrem/pour-qui-faut-il-voter" %></p>
      </footer>

    </div> <!-- /container -->

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= ENV['ANALYTICS'] %>', '<%= ENV['ANALYTICS_DOMAIN'] %>');
      ga('send', 'pageview');

    </script>

  </body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Pour qui faut-il voter ?</title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <link href='https://fonts.googleapis.com/css?family=Roboto:300,100' rel='stylesheet' type='text/css'>

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>



    <div class="container-fluid">
      <%= yield %>


      <footer>
        <p>Made with love in A406 - <%= link_to "Fork me on GitHub", "https://github.com/allegrem/pour-qui-faut-il-voter" %></p>
      </footer>

    </div> <!-- /container -->

    <script>
      (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
      (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
      m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
      })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

      ga('create', '<%= ENV['ANALYTICS'] %>', '<%= ENV['ANALYTICS_DOMAIN'] %>');
      ga('send', 'pageview');

    </script>

  </body>
</html>

app/views/logs/index.html.erb
<h1>Logs</h1>

<table class="logs-table">
  <thead>
    <tr>
      <th>Date</th>
      <th>Admin</th>
      <th>Item ID</th>
      <th>Content</th>
    </tr>
  </thead>
  <tbody>
    <% @logs.each do |l| %>
    <tr>
      <td><%= l.created_at %></td>
      <td><%= l.admin.name %></td>
      <td><%= l.item_id %></td>
      <td><%= l.content %></td>
    </tr>
    <% end %>
  </tbody>
</table>